### ISSUE TITLE
Adding a function to find a tournament by owner

### ISSUE THREAD

**Issue by Necroshruikan** [JeremySkalla/pysmashgg#1]
Hi, would be amazing to have a set of function/query to return a list of tournaments by owner, like here : https://developer.smash.gg/docs/examples/queries/tournaments-by-owner

What do you think ?

**Comment by JeremySkalla** [comment]
Yeah for sure I can get on that! Good suggestion! I needed to update it anyways to slightly change the events_dated_etc function anyways so, this should be out within the next 2 days :)

**Comment by JeremySkalla** [comment]
Just released v1.2 with the function you asked for plus a slight change. Let me know if you have any issues!
